### ISSUE TITLE
MOOM Week 1: The Object-Oriented Idea

### ISSUE THREAD

**Issue by jxandery** [jxandery/jxandery.github.io#27]
- [ ] What does it mean to be object-oriented?
- [ ] The Capacitor Sessions #1: Introductions
- [ ] Understanding late-binding with "barewords"
- [ ] The Capacitor Sessions #2: Better documentation through better errors
- [ ] Methods vs. Messages
- [ ] Q&A #1 with guest Betsy Haibel
- [ ] The Capacitor Sessions #2.1: Oh, Mailcatcher!
- [ ] Supplement: Smalltalk and the History of OOP
