### ISSUE TITLE
MOOM Week 2: Representing User Input

### ISSUE THREAD

**Issue by jxandery** [jxandery/jxandery.github.io#28]
- [ ] Representing Information with Objects
- [ ] The Capacitor Sessions #3: Failure Hints
- [ ] User input and the problem of primitive obsession
- [ ] The Capacitor Sessions #4: Understanding the problem
- [ ] Representing user input with Whole Values
- [ ] The Capacitor Sessions #5: Beginning a feature spec
- [ ] Invalid input, and the parallel hierarchy code smell
- [ ] The Capacitor Sessions #6: Let's commit to running with the ugly
- [ ] Representing invalid inputs with Exceptional Values
- [ ] Q&A #2 with Ben Orenstein
- [ ] Supplement: The CHECKS Pattern Language
- [ ] Supplement: Overcoming Stringly-Typed Ruby
